// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.

#pragma once

#include "botlib_adapter.hpp"

#include <cstdint>

struct gentity_t;

enum class BotNavMoverRidePhase {
	None = 0,
	Wait = 1,
	Board = 2,
	Ride = 3,
	Leave = 4,
};

struct BotNavRecoveryMove {
	int sideSign = 0;
	int framesRemaining = 0;
	bool hasMovement = false;
	float forwardMove = 0.0f;
	float sideMove = 0.0f;
	bool wait = false;
	bool use = false;
	int interactionAction = 0;
	int interactionKind = 0;
	int interactionEntity = -1;
};

struct BotNavRouteRequest {
	bool hasPositionGoal = false;
	float positionGoal[3] = {};
	bool hasInteractionArrivalGoal = false;
	int interactionArrivalEntityNumber = -1;
	int interactionArrivalKind = 0;
	int interactionArrivalAction = 0;
	bool hasTravelTypeGoal = false;
	int travelTypeGoal = 0;
};

struct BotNavInteractionGoal {
	int entityNumber = -1;
	int kind = 0;
	int action = 0;
	int area = 0;
	int source = 0;
	int distanceSquared = 0;
	int destinationDistanceSquared = 0;
	float position[3] = {};
};

struct BotNavRouteStatus {
	int requests = 0;
	int queries = 0;
	int refreshes = 0;
	int reuses = 0;
	int failures = 0;
	int routeRecomputeRateLimitChecks = 0;
	int routeRecomputeRateLimitReuses = 0;
	int routeRecomputeRateLimitRefreshes = 0;
	uint64_t routeQueryCpuNs = 0;
	int routeQueryCpuSamples = 0;
	uint64_t routeQueryCpuMaxNs = 0;
	uint64_t routeQueryCpuFailNs = 0;
	int routeQueryCpuFailSamples = 0;
	uint64_t routeReuseCpuNs = 0;
	int routeReuseCpuSamples = 0;
	int invalidSlots = 0;
	int cadenceRefreshes = 0;
	int targetRefreshes = 0;
	int driftRefreshes = 0;
	int preferredGoalRefreshes = 0;
	int routeTargetStabilizationChecks = 0;
	int routeTargetStabilizations = 0;
	int routeTargetStabilizationSkips = 0;
	int cornerCutChecks = 0;
	int cornerCutTraceAttempts = 0;
	int cornerCutTracePasses = 0;
	int cornerCutTraceFailures = 0;
	int cornerCutGroundTraceAttempts = 0;
	int cornerCutGroundTraceFailures = 0;
	int cornerCutApplications = 0;
	int cornerCutSkips = 0;
	int stuckChecks = 0;
	int stuckStalls = 0;
	int stuckDetections = 0;
	int stuckTargetReachedProgresses = 0;
	int stuckConsumedTargetStalls = 0;
	int stuckRepathRefreshes = 0;
	int stuckRecoveryActivations = 0;
	int stuckRecoveryFrames = 0;
	int stuckRecoveryProbeChecks = 0;
	int stuckRecoveryProbeUses = 0;
	int stuckRecoveryProbeBlocks = 0;
	int stuckRecoveryProbeFallbacks = 0;
	int persistentGoalRequests = 0;
	int persistentGoalAssignments = 0;
	int persistentGoalCacheReuses = 0;
	int persistentGoalClears = 0;
	int persistentGoalFallbacks = 0;
	int failedGoalEvents = 0;
	int itemGoalScans = 0;
	int itemGoalCandidates = 0;
	int itemGoalAssignments = 0;
	int itemGoalReuses = 0;
	int itemGoalDesirabilityUpdates = 0;
	int itemGoalDesirabilityCacheReuses = 0;
	int itemGoalDesirabilityStaggerDeferrals = 0;
	int itemGoalClears = 0;
	int itemGoalReservationSkips = 0;
	int itemGoalActiveReservations = 0;
	int itemGoalPeakActiveReservations = 0;
	int itemGoalBlacklistActivations = 0;
	int itemGoalBlacklistSkips = 0;
	int itemGoalBlacklistActive = 0;
	int ffaItemRoleEvaluations = 0;
	int ffaItemRoleSelections = 0;
	int ffaItemRoleScoreBoosts = 0;
	int ffaItemRoleSelectedGoals = 0;
	int ffaItemRoleInvalidSkips = 0;
	int ctfItemRoleEvaluations = 0;
	int ctfItemRoleSelections = 0;
	int ctfItemRoleScoreBoosts = 0;
	int ctfItemRoleSelectedGoals = 0;
	int ctfItemRoleInvalidSkips = 0;
	int teamItemRoleEvaluations = 0;
	int teamItemRoleSelections = 0;
	int teamItemRoleScoreBoosts = 0;
	int teamItemRoleSelectedGoals = 0;
	int teamItemRoleInvalidSkips = 0;
	int teamResourceDenialEvaluations = 0;
	int teamResourceDenialPolicyDenies = 0;
	int teamResourceDenialScoreBoosts = 0;
	int teamResourceDenialSelectedGoals = 0;
	int teamResourceDenialInvalidSkips = 0;
	int positionGoalRequests = 0;
	int positionGoalResolved = 0;
	int positionGoalAssignments = 0;
	int positionGoalCacheReuses = 0;
	int positionGoalClears = 0;
	int travelTypeGoalRequests = 0;
	int travelTypeGoalResolved = 0;
	int travelTypeGoalAssignments = 0;
	int travelTypeGoalCacheReuses = 0;
	int travelTypeGoalClears = 0;
	int travelTypeGoalSupportChecks = 0;
	int travelTypeGoalSupported = 0;
	int travelTypeGoalUnsupported = 0;
	int teleporterEntityGoalRequests = 0;
	int teleporterEntityGoalCandidates = 0;
	int teleporterEntityGoalResolved = 0;
	int teleporterEntityGoalAssignments = 0;
	int teleporterEntityGoalFallbacks = 0;
	int teleporterEntityGoalInvalidSkips = 0;
	int interactionGoalRequests = 0;
	int interactionGoalCandidates = 0;
	int interactionGoalResolved = 0;
	int interactionGoalInvalidSkips = 0;
	int interactionArrivalGoalRequests = 0;
	int interactionArrivalGoalCandidates = 0;
	int interactionArrivalGoalResolved = 0;
	int interactionArrivalGoalInvalidSkips = 0;
	int interactionArrivalMoverEndpointChecks = 0;
	int interactionArrivalMoverEndpointCandidates = 0;
	int interactionArrivalMoverEndpointSelections = 0;
	int interactionArrivalRouteRequests = 0;
	int interactionArrivalRouteAssignments = 0;
	int interactionArrivalRouteCacheReuses = 0;
	int interactionArrivalRouteReached = 0;
	int interactionArrivalRouteInvalidSkips = 0;
	int interactionMoverRideChecks = 0;
	int interactionMoverRideWaitStates = 0;
	int interactionMoverRideBoardStates = 0;
	int interactionMoverRideRideStates = 0;
	int interactionMoverRideLeaveStates = 0;
	int interactionMoverRideGroundStates = 0;
	int interactionMoverRideMovingStates = 0;
	int interactionMoverRideInvalidSkips = 0;
	int naturalMovementSupportAasLoaded = 0;
	int naturalMovementSupportChecks = 0;
	int naturalMovementSupported = 0;
	int naturalMovementUnsupported = 0;
	int naturalMovementUnsupportedMask = 0;
	int naturalMovementCrouchSupported = 0;
	int naturalMovementCrouchUnsupported = 0;
	int naturalMovementCrouchReason = 0;
	int naturalMovementCrouchArea = 0;
	int naturalMovementCrouchGoalArea = 0;
	int naturalMovementCrouchOriginX = 0;
	int naturalMovementCrouchOriginY = 0;
	int naturalMovementCrouchOriginZ = 0;
	int naturalMovementSwimSupported = 0;
	int naturalMovementSwimUnsupported = 0;
	int naturalMovementSwimReason = 0;
	int naturalMovementSwimArea = 0;
	int naturalMovementSwimGoalArea = 0;
	int naturalMovementSwimOriginX = 0;
	int naturalMovementSwimOriginY = 0;
	int naturalMovementSwimOriginZ = 0;
	int naturalMovementWaterJumpSupported = 0;
	int naturalMovementWaterJumpUnsupported = 0;
	int naturalMovementWaterJumpReason = 0;
	int naturalMovementWaterJumpArea = 0;
	int naturalMovementWaterJumpGoalArea = 0;
	int naturalMovementWaterJumpOriginX = 0;
	int naturalMovementWaterJumpOriginY = 0;
	int naturalMovementWaterJumpOriginZ = 0;
	int interactionChecks = 0;
	int interactionCandidates = 0;
	int interactionActivations = 0;
	int interactionStuckActivations = 0;
	int interactionElevatorActivations = 0;
	int interactionWaitFrames = 0;
	int interactionUseFrames = 0;
	int interactionMisses = 0;
	int interactionProgressionCandidates = 0;
	int interactionProgressionSelections = 0;
	int interactionProgressionPreferenceSelections = 0;
	int interactionProgressionTargetEntitySelections = 0;
	int interactionProgressionTargetSelections = 0;
	int interactionProgressionTargetLinkSelections = 0;
	int interactionProgressionNamedTargetSelections = 0;
	int interactionProgressionKeyEntitySelections = 0;
	int interactionProgressionKeyPathCandidates = 0;
	int interactionProgressionKeyPathSelections = 0;
	int interactionProgressionKeyPathCompletions = 0;
	int interactionProgressionCompletions = 0;
	int interactionProgressionPostRefreshes = 0;
	int interactionProgressionPostFrames = 0;
	int interactionProgressionRepeatSuppressions = 0;
	int interactionProgressionCarryCompletions = 0;
	int interactionProgressionCarryDistinctCompletions = 0;
	int interactionProgressionCompletedClients = 0;
	int interactionProgressionDistinctCompletedClients = 0;
	int interactionWorldEntities = 0;
	int interactionWorldDoors = 0;
	int interactionWorldButtons = 0;
	int interactionWorldPlatforms = 0;
	int interactionWorldTrains = 0;
	int interactionWorldWaters = 0;
	int interactionWorldTriggers = 0;
	int interactionWorldMovers = 0;
	int interactionWorldTeleporters = 0;
	int interactionWorldHazards = 0;
	int interactionWorldUseEntities = 0;
	int interactionWorldTouchEntities = 0;
	int interactionWorldTargetEntities = 0;
	int interactionWorldProgressionTargets = 0;
	int interactionWorldTargetLinks = 0;
	int interactionWorldNamedTargets = 0;
	int interactionWorldKeyEntities = 0;
	int interactionWorldKeyItems = 0;
	int interactionWorldKeyLocks = 0;
	int interactionWorldKeyPathEntities = 0;
	int interactionWorldProgressionEntities = 0;
	int debugOverlayFrames = 0;
	int debugOverlayRoutes = 0;
	int debugOverlayGoals = 0;
	int debugOverlayMissingFrames = 0;
	int debugOverlayLines = 0;
	int debugOverlayCrosses = 0;
	int debugOverlayArrows = 0;
	int debugOverlayLabels = 0;
	int debugOverlayPolylinePoints = 0;
	int debugOverlayPolylineSegments = 0;
	int debugOverlayFilteredSlots = 0;
	int debugOverlayFilterMissFrames = 0;
	int lastClient = -1;
	int lastDebugClient = -1;
	int lastDebugFilterClient = -1;
	int lastPersistentGoalArea = 0;
	int lastItemGoalEntity = -1;
	int lastItemGoalArea = 0;
	int lastItemGoalItem = 0;
	int lastItemGoalScore = 0;
	int lastItemGoalDesirabilityClient = -1;
	int lastItemGoalDesirabilityNextFrame = 0;
	int lastItemGoalReservedEntity = -1;
	int lastItemGoalReservedByClient = -1;
	int lastItemGoalBlacklistedEntity = -1;
	int lastItemGoalBlacklistedByClient = -1;
	int lastItemGoalBlacklistFramesRemaining = 0;
	int lastFfaItemRoleClient = -1;
	int lastFfaItemRoleMode = 0;
	int lastFfaItemRoleRole = 0;
	int lastFfaItemRoleLane = 0;
	int lastFfaItemRoleCategory = 0;
	int lastFfaItemRoleItemRole = 0;
	int lastFfaItemRolePriority = 0;
	int lastFfaItemRoleScoreBoost = 0;
	int lastFfaItemRoleProfileItemBonus = 0;
	int lastFfaItemRoleEntity = -1;
	int lastFfaItemRoleItem = 0;
	int lastFfaItemRoleScore = 0;
	int lastCtfItemRoleClient = -1;
	int lastCtfItemRoleMode = 0;
	int lastCtfItemRoleRole = 0;
	int lastCtfItemRoleLane = 0;
	int lastCtfItemRoleCategory = 0;
	int lastCtfItemRoleItemRole = 0;
	int lastCtfItemRolePriority = 0;
	int lastCtfItemRoleScoreBoost = 0;
	int lastCtfItemRoleProfileItemBonus = 0;
	int lastCtfItemRoleEntity = -1;
	int lastCtfItemRoleItem = 0;
	int lastCtfItemRoleScore = 0;
	int lastTeamItemRoleClient = -1;
	int lastTeamItemRoleMode = 0;
	int lastTeamItemRoleRole = 0;
	int lastTeamItemRoleLane = 0;
	int lastTeamItemRoleCategory = 0;
	int lastTeamItemRoleItemRole = 0;
	int lastTeamItemRolePriority = 0;
	int lastTeamItemRoleScoreBoost = 0;
	int lastTeamItemRoleProfileItemBonus = 0;
	int lastTeamItemRoleEntity = -1;
	int lastTeamItemRoleItem = 0;
	int lastTeamItemRoleScore = 0;
	int lastTeamResourceDenialClient = -1;
	int lastTeamResourceDenialMode = 0;
	int lastTeamResourceDenialRole = 0;
	int lastTeamResourceDenialLane = 0;
	int lastTeamResourceDenialCategory = 0;
	int lastTeamResourceDenialIntent = 0;
	int lastTeamResourceDenialPriority = 0;
	int lastTeamResourceDenialScoreBoost = 0;
	int lastTeamResourceDenialProfileItemBonus = 0;
	int lastTeamResourceDenialEntity = -1;
	int lastTeamResourceDenialItem = 0;
	int lastTeamResourceDenialScore = 0;
	int lastPositionGoalArea = 0;
	int lastPositionGoalX = 0;
	int lastPositionGoalY = 0;
	int lastPositionGoalZ = 0;
	int lastTravelTypeGoalType = 0;
	int lastTravelTypeGoalArea = 0;
	int lastTravelTypeGoalSupportType = 0;
	int lastTravelTypeGoalSupportArea = 0;
	int lastTravelTypeGoalSupportGoalArea = 0;
	int lastTeleporterEntityGoalEntity = -1;
	int lastTeleporterEntityGoalArea = 0;
	int lastTeleporterEntityGoalX = 0;
	int lastTeleporterEntityGoalY = 0;
	int lastTeleporterEntityGoalZ = 0;
	int lastTeleporterEntityGoalDistanceSq = 0;
	int lastTeleporterEntityGoalAction = 0;
	int lastInteractionGoalEntity = -1;
	int lastInteractionGoalKind = 0;
	int lastInteractionGoalAction = 0;
	int lastInteractionGoalArea = 0;
	int lastInteractionGoalX = 0;
	int lastInteractionGoalY = 0;
	int lastInteractionGoalZ = 0;
	int lastInteractionGoalDistanceSq = 0;
	int lastInteractionGoalDestinationDistanceSq = 0;
	int lastInteractionArrivalGoalEntity = -1;
	int lastInteractionArrivalGoalKind = 0;
	int lastInteractionArrivalGoalAction = 0;
	int lastInteractionArrivalGoalArea = 0;
	int lastInteractionArrivalGoalSource = 0;
	int lastInteractionArrivalGoalX = 0;
	int lastInteractionArrivalGoalY = 0;
	int lastInteractionArrivalGoalZ = 0;
	int lastInteractionArrivalGoalDistanceSq = 0;
	int lastInteractionArrivalGoalDestinationDistanceSq = 0;
	int lastInteractionArrivalMoverEndpointEntity = -1;
	int lastInteractionArrivalMoverEndpointKind = 0;
	int lastInteractionArrivalMoverEndpointAction = 0;
	int lastInteractionArrivalMoverEndpointArea = 0;
	int lastInteractionArrivalMoverEndpointX = 0;
	int lastInteractionArrivalMoverEndpointY = 0;
	int lastInteractionArrivalMoverEndpointZ = 0;
	int lastInteractionArrivalMoverEndpointDistanceSq = 0;
	int lastInteractionArrivalMoverEndpointDestinationDistanceSq = 0;
	int lastInteractionArrivalRouteEntity = -1;
	int lastInteractionArrivalRouteKind = 0;
	int lastInteractionArrivalRouteAction = 0;
	int lastInteractionArrivalRouteArea = 0;
	int lastInteractionArrivalRouteX = 0;
	int lastInteractionArrivalRouteY = 0;
	int lastInteractionArrivalRouteZ = 0;
	int lastInteractionArrivalRouteDistanceSq = 0;
	int lastInteractionMoverRidePhase = 0;
	int lastInteractionMoverRideEntity = -1;
	int lastInteractionMoverRideKind = 0;
	int lastInteractionMoverRideAction = 0;
	int lastInteractionMoverRideArea = 0;
	int lastInteractionMoverRideClient = -1;
	int lastInteractionMoverRideMoveState = 0;
	int lastInteractionMoverRideGroundEntity = -1;
	int lastInteractionMoverRideX = 0;
	int lastInteractionMoverRideY = 0;
	int lastInteractionMoverRideZ = 0;
	int lastInteractionMoverRideDistanceSq = 0;
	int lastInteractionAction = 0;
	int lastInteractionKind = 0;
	int lastInteractionEntity = -1;
	int lastInteractionClient = -1;
	int lastInteractionSpawnCount = 0;
	int lastInteractionDistanceSq = 0;
	int lastInteractionTravelType = 0;
	int lastInteractionMoveState = 0;
	int lastInteractionFramesRemaining = 0;
	int lastInteractionProgressionScore = 0;
	int lastInteractionProgressionPreferred = 0;
	int lastInteractionTargetEntity = 0;
	int lastInteractionProgressionTarget = 0;
	int lastInteractionTargetLink = 0;
	int lastInteractionNamedTarget = 0;
	int lastInteractionKeyEntity = 0;
	int lastInteractionKeyItem = 0;
	int lastInteractionKeyLock = 0;
	int lastInteractionKeyRequiredItem = 0;
	int lastInteractionProgressionCompletedEntity = -1;
	int lastInteractionProgressionCompletedScore = 0;
	int lastInteractionProgressionKeyPathEntity = -1;
	int lastInteractionProgressionKeyPathScore = 0;
	int lastInteractionProgressionKeyPathKeyItem = 0;
	int lastInteractionProgressionKeyPathKeyLock = 0;
	int lastInteractionProgressionKeyPathRequiredItem = 0;
	int lastInteractionProgressionPostEntity = -1;
	int lastInteractionProgressionPostFramesRemaining = 0;
	int lastInteractionProgressionSuppressedEntity = -1;
	int lastInteractionProgressionSuppressedScore = 0;
	int lastInteractionProgressionCarryPreviousEntity = -1;
	int lastInteractionProgressionCarryEntity = -1;
	int lastInteractionProgressionCarryDistinct = 0;
	int lastInteractionProgressionCarryCount = 0;
	int lastInteractionProgressionCarryDistinctCount = 0;
	int lastInteractionOriginX = 0;
	int lastInteractionOriginY = 0;
	int lastInteractionOriginZ = 0;
	int lastInteractionBoundsMinX = 0;
	int lastInteractionBoundsMinY = 0;
	int lastInteractionBoundsMinZ = 0;
	int lastInteractionBoundsMaxX = 0;
	int lastInteractionBoundsMaxY = 0;
	int lastInteractionBoundsMaxZ = 0;
	int lastInteractionUse = 0;
	int lastInteractionTouch = 0;
	int lastInteractionSolid = 0;
	int lastInteractionMoveType = 0;
	int lastGoalClearReason = 0;
	int lastFailedGoalReason = 0;
	int lastFailedGoalClient = -1;
	int lastFailedGoalArea = 0;
	int lastFailedGoalEntity = -1;
	int lastFailedGoalItem = 0;
	int lastStuckReason = 0;
	int lastStuckClient = -1;
	int lastStuckFrames = 0;
	int lastStuckDistanceSq = 0;
	int lastStuckTargetDistanceSq = 0;
	int lastStuckProgressDelta = 0;
	int lastStuckConsumedTarget = 0;
	int lastStuckRecoveryClient = -1;
	int lastStuckRecoverySide = 0;
	int lastStuckRecoveryFramesRemaining = 0;
	int lastStuckRecoveryProbeCandidate = -1;
	int lastStuckRecoveryProbeFraction = 0;
	int lastStuckRecoveryForwardMove = 0;
	int lastStuckRecoverySideMove = 0;
	int lastCurrentArea = 0;
	int lastStartArea = 0;
	int lastGoalArea = 0;
	int lastRouteEndArea = 0;
	int lastRoutePointCount = 0;
	int lastRouteTargetOriginalDistanceSq = 0;
	int lastRouteTargetStableDistanceSq = 0;
	int lastRouteTargetStablePointIndex = -1;
	int lastCornerCutPointIndex = -1;
	int lastCornerCutOriginalPointCount = 0;
	int lastCornerCutResultPointCount = 0;
	int lastCornerCutDistanceSq = 0;
	int lastCornerCutTraceFraction = 0;
	int lastCornerCutTravelType = 0;
	int lastCornerCutSkipReason = 0;
	int lastTravelTime = 0;
	int lastReachability = 0;
	int lastReachabilityTravelType = 0;
	int lastReachabilityTravelFlags = 0;
	int lastReachabilityEndArea = 0;
	int lastStopEvent = 0;
};

struct BotNavBlackboardSnapshot {
	bool routeSlotValid = false;
	int clientIndex = -1;
	int goalType = 0;
	int goalArea = 0;
	int goalEntity = -1;
	int goalSpawnCount = 0;
	int goalItem = 0;
	int goalPositionX = 0;
	int goalPositionY = 0;
	int goalPositionZ = 0;
	int goalTravelType = 0;
	int routeStartArea = 0;
	int routeGoalArea = 0;
	int routeEndArea = 0;
	int routePointCount = 0;
	int routeTravelTime = 0;
	int routeReachability = 0;
	int routeReachabilityTravelType = 0;
	int routeReachabilityTravelFlags = 0;
	int routeReachabilityEndArea = 0;
	int routeStopEvent = 0;
	int stuckReason = 0;
	int stuckFrames = 0;
	int stuckDistanceSq = 0;
	int stuckProgressDelta = 0;
	int stuckRecoverySide = 0;
	int stuckRecoveryFramesRemaining = 0;
	int itemReservationActive = 0;
	int itemReservationEntity = -1;
	int itemReservationOwnerClient = -1;
	int itemReservationItem = 0;
	int itemReservationArea = 0;
};

void BotNav_ResetAll();
void BotNav_ResetClient(int clientIndex);
bool BotNav_ProbePickupGoal(const gentity_t *bot);
bool BotNav_GetRouteSteer(const gentity_t *bot, const BotNavRouteRequest *request, BotLibAdapterRouteSteer *route);
bool BotNav_RouteTargetTraceClear(
	const gentity_t *bot,
	const BotLibAdapterRouteSteer *route,
	const float target[3]);
bool BotNav_FindInteractionGoal(const gentity_t *bot, int requiredKind, BotNavInteractionGoal *goal);
bool BotNav_FindInteractionArrivalGoal(
	const gentity_t *bot,
	int interactionEntityNumber,
	const float destination[3],
	BotNavInteractionGoal *goal);
bool BotNav_SetInteractionArrivalRouteRequest(
	const BotNavInteractionGoal &goal,
	BotNavRouteRequest *request);
bool BotNav_BuildInteractionArrivalRouteRequest(
	const gentity_t *bot,
	int interactionEntityNumber,
	const float destination[3],
	BotNavRouteRequest *request,
	BotNavInteractionGoal *goal);
bool BotNav_InteractionArrivalRouteReached(
	const gentity_t *bot,
	const BotNavInteractionGoal *goal,
	int distanceSquaredThreshold);
bool BotNav_RecordMoverRideState(
	const gentity_t *bot,
	int interactionEntityNumber,
	BotNavMoverRidePhase phase,
	const BotNavInteractionGoal *goal = nullptr);
bool BotNav_RequestInteractionRetry(
	const gentity_t *bot,
	const BotLibAdapterRouteSteer *route,
	bool fromStuck);
bool BotNav_ActivateInteractionNearPosition(
	const gentity_t *bot,
	const float position[3],
	int requiredKind,
	int forcedTravelType);
bool BotNav_GetRecoveryMove(const gentity_t *bot, BotNavRecoveryMove *move);
bool BotNav_GetRecoveryMove(const gentity_t *bot, const float viewAngles[3], BotNavRecoveryMove *move);
bool BotNav_DrawDebugOverlay(bool drawRoute, bool drawGoal, int debugClientIndex);
const BotNavRouteStatus &BotNav_GetRouteStatus();
bool BotNav_GetBlackboardSnapshot(int clientIndex, BotNavBlackboardSnapshot *snapshot);
